package com.yshyerp.vehicle.mapper;

import com.yshyerp.vehicle.entity.EDrumtmp;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface EDrumtmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_drumtmp
     *
     * @mbggenerated
     */
    int insert(EDrumtmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_drumtmp
     *
     * @mbggenerated
     */
    int insertSelective(EDrumtmp record);
}