package com.yshyerp.vehicle.mapper;

import com.yshyerp.vehicle.entity.VehiPlan;
import com.yshyerp.vehicle.entity.VehiPlan1;

import java.util.List;

public interface VehiPlanMapper {
    /**
     * 新增 来桶计划
     * @mbggenerated
     */
    int insert(VehiPlan1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehi_plan
     *
     * @mbggenerated
     */
    int insertSelective(VehiPlan record);

    //查询VehiPlan全部信息
    List<VehiPlan> list();

    //根据提pLlanNo 查询信息
    public VehiPlan queryplanNoByDoNo(String planNo);
}