package com.yshyerp.vehicle.service;

import com.yshyerp.vehicle.entity.EDrumtmp;



public interface EDrumtmpService {
    /**
     * 新增
     *
     * @mbggenerated
     */
    int insert(EDrumtmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_drumtmp
     *
     * @mbggenerated
     */
    int insertSelective(EDrumtmp record);
}