package com.yshyerp.vehicle.entity;


import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

 //工作单
@Data
public class Djob1 implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.e_name
     *
     * @mbggenerated
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.to
     *
     * @mbggenerated
     */
    private String to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.crr_no
     *
     * @mbggenerated
     */
    private String crrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.applied_no
     *
     * @mbggenerated
     */
    private String appliedNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.plan_no
     *
     * @mbggenerated
     */
    private String planNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.s_customer
     *
     * @mbggenerated
     */
    private String scustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.date_com
     *
     * @mbggenerated
     */
    private Date dateCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.date_exe
     *
     * @mbggenerated
     */
    private Date dateExe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.vehicle
     *
     * @mbggenerated
     */
    private String vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.tank
     *
     * @mbggenerated
     */
    private String tank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.kgs
     *
     * @mbggenerated
     */
    private Short kgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.new
     *
     * @mbggenerated
     */
    private String n;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.c_new
     *
     * @mbggenerated
     */
    private String cnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.drums
     *
     * @mbggenerated
     */
    private Integer drums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.total
     *
     * @mbggenerated
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.charge
     *
     * @mbggenerated
     */
    private Boolean charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.tare
     *
     * @mbggenerated
     */
    private BigDecimal tare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.batch
     *
     * @mbggenerated
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.slop
     *
     * @mbggenerated
     */
    private Boolean slop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.drum_req
     *
     * @mbggenerated
     */
    private Short drumReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.code1
     *
     * @mbggenerated
     */
    private String code1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.code2
     *
     * @mbggenerated
     */
    private String code2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.code3
     *
     * @mbggenerated
     */
    private String code3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.p_bar
     *
     * @mbggenerated
     */
    private Short pBar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.requ_2
     *
     * @mbggenerated
     */
    private String requ2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.requ_3
     *
     * @mbggenerated
     */
    private String requ3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.requ_4
     *
     * @mbggenerated
     */
    private String requ4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.requ_5
     *
     * @mbggenerated
     */
    private String requ5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.requ_6
     *
     * @mbggenerated
     */
    private String requ6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.drum_fill
     *
     * @mbggenerated
     */
    private Boolean drumFill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.clean
     *
     * @mbggenerated
     */
    private String clean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.affrim
     *
     * @mbggenerated
     */
    private Boolean affrim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.balance
     *
     * @mbggenerated
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.fee_cust
     *
     * @mbggenerated
     */
    private String feeCust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column djob.flag
     *
     * @mbggenerated
     */
    private Short flag;


    private String types;

    private String fno;

    public String getFno() {
        return fno;
    }

    public void setFno(String fno) {
        this.fno = fno;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table djob
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public void setTypes(String types) {
        this.types = types;
    }


    public String getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.no
     *
     * @return the value of djob.no
     *
     * @mbggenerated
     */




    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.no
     *
     * @param no the value for djob.no
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.d
     *
     * @return the value of djob.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.d
     *
     * @param d the value for djob.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.e_name
     *
     * @return the value of djob.e_name
     *
     * @mbggenerated
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.e_name
     *
     * @param eName the value for djob.e_name
     *
     * @mbggenerated
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.c_name
     *
     * @return the value of djob.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.c_name
     *
     * @param cName the value for djob.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.status
     *
     * @return the value of djob.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.status
     *
     * @param status the value for djob.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.to
     *
     * @return the value of djob.to
     *
     * @mbggenerated
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.to
     *
     * @param to the value for djob.to
     *
     * @mbggenerated
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.crr_no
     *
     * @return the value of djob.crr_no
     *
     * @mbggenerated
     */
    public String getCrrNo() {
        return crrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.crr_no
     *
     * @param crrNo the value for djob.crr_no
     *
     * @mbggenerated
     */
    public void setCrrNo(String crrNo) {
        this.crrNo = crrNo == null ? null : crrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.applied_no
     *
     * @return the value of djob.applied_no
     *
     * @mbggenerated
     */
    public String getAppliedNo() {
        return appliedNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.applied_no
     *
     * @param appliedNo the value for djob.applied_no
     *
     * @mbggenerated
     */
    public void setAppliedNo(String appliedNo) {
        this.appliedNo = appliedNo == null ? null : appliedNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.plan_no
     *
     * @return the value of djob.plan_no
     *
     * @mbggenerated
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.plan_no
     *
     * @param planNo the value for djob.plan_no
     *
     * @mbggenerated
     */
    public void setPlanNo(String planNo) {
        this.planNo = planNo == null ? null : planNo.trim();
    }



    public String getCustomer() {
        return customer;
    }


    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    public Date getDateCom() {
        return dateCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.date_com
     *
     * @param dateCom the value for djob.date_com
     *
     * @mbggenerated
     */
    public void setDateCom(Date dateCom) {
        this.dateCom = dateCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.date_exe
     *
     * @return the value of djob.date_exe
     *
     * @mbggenerated
     */
    public Date getDateExe() {
        return dateExe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.date_exe
     *
     * @param dateExe the value for djob.date_exe
     *
     * @mbggenerated
     */
    public void setDateExe(Date dateExe) {
        this.dateExe = dateExe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.vehicle
     *
     * @return the value of djob.vehicle
     *
     * @mbggenerated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.vehicle
     *
     * @param vehicle the value for djob.vehicle
     *
     * @mbggenerated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.commodity
     *
     * @return the value of djob.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.commodity
     *
     * @param commodity the value for djob.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity == null ? null : commodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.tank
     *
     * @return the value of djob.tank
     *
     * @mbggenerated
     */
    public String getTank() {
        return tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.tank
     *
     * @param tank the value for djob.tank
     *
     * @mbggenerated
     */
    public void setTank(String tank) {
        this.tank = tank == null ? null : tank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.kgs
     *
     * @return the value of djob.kgs
     *
     * @mbggenerated
     */
    public Short getKgs() {
        return kgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.kgs
     *
     * @param kgs the value for djob.kgs
     *
     * @mbggenerated
     */
    public void setKgs(Short kgs) {
        this.kgs = kgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.new
     *
     * @return the value of djob.new
     *
     * @mbggenerated
     */
    public String getN() {
        return n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.new
     *

     *
     * @mbggenerated
     */
    public void setN(String n) {
        this.n = n == null ? null : n.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.c_new
     *
     * @return the value of djob.c_new
     *
     * @mbggenerated
     */
     public String getCnew() {
         return cnew;
     }

     public void setCnew(String cnew) {
         this.cnew = cnew;
     }

     /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.drums
     *
     * @return the value of djob.drums
     *
     * @mbggenerated
     */
    public Integer getDrums() {
        return drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.drums
     *
     * @param drums the value for djob.drums
     *
     * @mbggenerated
     */
    public void setDrums(Integer drums) {
        this.drums = drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.total
     *
     * @return the value of djob.total
     *
     * @mbggenerated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.total
     *
     * @param total the value for djob.total
     *
     * @mbggenerated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.color
     *
     * @return the value of djob.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.color
     *
     * @param color the value for djob.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.charge
     *
     * @return the value of djob.charge
     *
     * @mbggenerated
     */
    public Boolean getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.charge
     *
     * @param charge the value for djob.charge
     *
     * @mbggenerated
     */
    public void setCharge(Boolean charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.tare
     *
     * @return the value of djob.tare
     *
     * @mbggenerated
     */
    public BigDecimal getTare() {
        return tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.tare
     *
     * @param tare the value for djob.tare
     *
     * @mbggenerated
     */
    public void setTare(BigDecimal tare) {
        this.tare = tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.batch
     *
     * @return the value of djob.batch
     *
     * @mbggenerated
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.batch
     *
     * @param batch the value for djob.batch
     *
     * @mbggenerated
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.slop
     *
     * @return the value of djob.slop
     *
     * @mbggenerated
     */
    public Boolean getSlop() {
        return slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.slop
     *
     * @param slop the value for djob.slop
     *
     * @mbggenerated
     */
    public void setSlop(Boolean slop) {
        this.slop = slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.type
     *
     * @return the value of djob.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.type
     *
     * @param type the value for djob.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.drum_req
     *
     * @return the value of djob.drum_req
     *
     * @mbggenerated
     */
    public Short getDrumReq() {
        return drumReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.drum_req
     *
     * @param drumReq the value for djob.drum_req
     *
     * @mbggenerated
     */
    public void setDrumReq(Short drumReq) {
        this.drumReq = drumReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.code1
     *
     * @return the value of djob.code1
     *
     * @mbggenerated
     */
    public String getCode1() {
        return code1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.code1
     *
     * @param code1 the value for djob.code1
     *
     * @mbggenerated
     */
    public void setCode1(String code1) {
        this.code1 = code1 == null ? null : code1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.code2
     *
     * @return the value of djob.code2
     *
     * @mbggenerated
     */
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.code2
     *
     * @param code2 the value for djob.code2
     *
     * @mbggenerated
     */
    public void setCode2(String code2) {
        this.code2 = code2 == null ? null : code2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.code3
     *
     * @return the value of djob.code3
     *
     * @mbggenerated
     */
    public String getCode3() {
        return code3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.code3
     *
     * @param code3 the value for djob.code3
     *
     * @mbggenerated
     */
    public void setCode3(String code3) {
        this.code3 = code3 == null ? null : code3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.p_bar
     *
     * @return the value of djob.p_bar
     *
     * @mbggenerated
     */
    public Short getpBar() {
        return pBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.p_bar
     *
     * @param pBar the value for djob.p_bar
     *
     * @mbggenerated
     */
    public void setpBar(Short pBar) {
        this.pBar = pBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.label
     *
     * @return the value of djob.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.label
     *
     * @param label the value for djob.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.requ_2
     *
     * @return the value of djob.requ_2
     *
     * @mbggenerated
     */
    public String getRequ2() {
        return requ2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.requ_2
     *
     * @param requ2 the value for djob.requ_2
     *
     * @mbggenerated
     */
    public void setRequ2(String requ2) {
        this.requ2 = requ2 == null ? null : requ2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.requ_3
     *
     * @return the value of djob.requ_3
     *
     * @mbggenerated
     */
    public String getRequ3() {
        return requ3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.requ_3
     *
     * @param requ3 the value for djob.requ_3
     *
     * @mbggenerated
     */
    public void setRequ3(String requ3) {
        this.requ3 = requ3 == null ? null : requ3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.requ_4
     *
     * @return the value of djob.requ_4
     *
     * @mbggenerated
     */
    public String getRequ4() {
        return requ4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.requ_4
     *
     * @param requ4 the value for djob.requ_4
     *
     * @mbggenerated
     */
    public void setRequ4(String requ4) {
        this.requ4 = requ4 == null ? null : requ4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.requ_5
     *
     * @return the value of djob.requ_5
     *
     * @mbggenerated
     */
    public String getRequ5() {
        return requ5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.requ_5
     *
     * @param requ5 the value for djob.requ_5
     *
     * @mbggenerated
     */
    public void setRequ5(String requ5) {
        this.requ5 = requ5 == null ? null : requ5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.requ_6
     *
     * @return the value of djob.requ_6
     *
     * @mbggenerated
     */
    public String getRequ6() {
        return requ6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.requ_6
     *
     * @param requ6 the value for djob.requ_6
     *
     * @mbggenerated
     */
    public void setRequ6(String requ6) {
        this.requ6 = requ6 == null ? null : requ6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.remark
     *
     * @return the value of djob.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.remark
     *
     * @param remark the value for djob.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.drum_fill
     *
     * @return the value of djob.drum_fill
     *
     * @mbggenerated
     */
    public Boolean getDrumFill() {
        return drumFill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.drum_fill
     *
     * @param drumFill the value for djob.drum_fill
     *
     * @mbggenerated
     */
    public void setDrumFill(Boolean drumFill) {
        this.drumFill = drumFill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.clean
     *
     * @return the value of djob.clean
     *
     * @mbggenerated
     */
    public String getClean() {
        return clean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.clean
     *
     * @param clean the value for djob.clean
     *
     * @mbggenerated
     */
    public void setClean(String clean) {
        this.clean = clean == null ? null : clean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.affrim
     *
     * @return the value of djob.affrim
     *
     * @mbggenerated
     */
    public Boolean getAffrim() {
        return affrim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.affrim
     *
     * @param affrim the value for djob.affrim
     *
     * @mbggenerated
     */
    public void setAffrim(Boolean affrim) {
        this.affrim = affrim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.balance
     *
     * @return the value of djob.balance
     *
     * @mbggenerated
     */
     public Integer getBalance() {
         return balance;
     }

     public void setBalance(Integer balance) {
         this.balance = balance;
     }

     /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.fee_cust
     *
     * @return the value of djob.fee_cust
     *
     * @mbggenerated
     */
    public String getFeeCust() {
        return feeCust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.fee_cust
     *
     * @param feeCust the value for djob.fee_cust
     *
     * @mbggenerated
     */
    public void setFeeCust(String feeCust) {
        this.feeCust = feeCust == null ? null : feeCust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column djob.flag
     *
     * @return the value of djob.flag
     *
     * @mbggenerated
     */
    public Short getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column djob.flag
     *
     * @param flag the value for djob.flag
     *
     * @mbggenerated
     */
    public void setFlag(Short flag) {
        this.flag = flag;
    }


     public String getScustomer() {
         return scustomer;
     }

     public void setScustomer(String scustomer) {
         this.scustomer = scustomer;
     }
 }