package com.yshyerp.vehicle.entity;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@Data
public class Drumtmpout implements Serializable {
    public String getNameyy() {
        return nameyy;
    }

    public void setNameyy(String nameyy) {
        this.nameyy = nameyy;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.id
     *
     * @mbggenerated
     */
    private String nameyy;

    private Integer id;

    private int coun;

    public int getCoun() {
        return coun;
    }

    public void setCoun(int coun) {
        this.coun = coun;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.D
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.no
     *
     * @mbggenerated
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.ddc_no
     *
     * @mbggenerated
     */
    private String ddcNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.no1
     *
     * @mbggenerated
     */
    private String no1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.plan_no
     *
     * @mbggenerated
     */
    private String planNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.tank
     *
     * @mbggenerated
     */
    private String tank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.time_r
     *
     * @mbggenerated
     */
    private String timeR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.date1
     *
     * @mbggenerated
     */
    private Date date1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.time1
     *
     * @mbggenerated
     */
    private String time1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.weight1
     *
     * @mbggenerated
     */
    private Integer weight1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.date2
     *
     * @mbggenerated
     */
    private Date date2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.time2
     *
     * @mbggenerated
     */
    private String time2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.weight2
     *
     * @mbggenerated
     */
    private Integer weight2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.vehicle
     *
     * @mbggenerated
     */
    private String vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.vehicle1
     *
     * @mbggenerated
     */
    private String vehicle1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.t_customer
     *
     * @mbggenerated
     */
    private String tCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.c_customer
     *
     * @mbggenerated
     */
    private String cCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.s_customer
     *
     * @mbggenerated
     */
    private String sCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.billid
     *
     * @mbggenerated
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.crr_no
     *
     * @mbggenerated
     */
    private String crrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.do_no
     *
     * @mbggenerated
     */
    private String doNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.commodity1
     *
     * @mbggenerated
     */
    private String commodity1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.drums
     *
     * @mbggenerated
     */
    private Short drums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.packing
     *
     * @mbggenerated
     */
    private Integer packing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.netweight
     *
     * @mbggenerated
     */
    private Integer netweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.new
     *
     * @mbggenerated
     */
    private String n;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.tare
     *
     * @mbggenerated
     */
    private BigDecimal tare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.cover
     *
     * @mbggenerated
     */
    private Boolean cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.batch
     *
     * @mbggenerated
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.slop
     *
     * @mbggenerated
     */
    private Boolean slop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.delivered
     *
     * @mbggenerated
     */
    private String delivered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.serial
     *
     * @mbggenerated
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.isin
     *
     * @mbggenerated
     */
    private Boolean isin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.sendno
     *
     * @mbggenerated
     */
    private String sendno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.idno
     *
     * @mbggenerated
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.ori_do
     *
     * @mbggenerated
     */
    private Boolean oriDo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.faxno
     *
     * @mbggenerated
     */
    private String faxno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.charge
     *
     * @mbggenerated
     */
    private Boolean charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.fee_no
     *
     * @mbggenerated
     */
    private String feeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.fee
     *
     * @mbggenerated
     */
    private Short fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.jobno
     *
     * @mbggenerated
     */
    private String jobno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drumtmp.p_bar
     *
     * @mbggenerated
     */
    private Boolean pBar;

    public String getVehiclea() {
        return vehiclea;
    }

    public void setVehiclea(String vehiclea) {
        this.vehiclea = vehiclea;
    }

    private String  vehiclea;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drumtmp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.id
     *
     * @return the value of drumtmp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.id
     *
     * @param id the value for drumtmp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.D
     *
     * @return the value of drumtmp.D
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.D
     *
     * @param d the value for drumtmp.D
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.no
     *
     * @return the value of drumtmp.no
     *
     * @mbggenerated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.no
     *
     * @param no the value for drumtmp.no
     *
     * @mbggenerated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.ddc_no
     *
     * @return the value of drumtmp.ddc_no
     *
     * @mbggenerated
     */
    public String getDdcNo() {
        return ddcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.ddc_no
     *
     * @param ddcNo the value for drumtmp.ddc_no
     *
     * @mbggenerated
     */
    public void setDdcNo(String ddcNo) {
        this.ddcNo = ddcNo == null ? null : ddcNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.no1
     *
     * @return the value of drumtmp.no1
     *
     * @mbggenerated
     */
    public String getNo1() {
        return no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.no1
     *
     * @param no1 the value for drumtmp.no1
     *
     * @mbggenerated
     */
    public void setNo1(String no1) {
        this.no1 = no1 == null ? null : no1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.plan_no
     *
     * @return the value of drumtmp.plan_no
     *
     * @mbggenerated
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.plan_no
     *
     * @param planNo the value for drumtmp.plan_no
     *
     * @mbggenerated
     */
    public void setPlanNo(String planNo) {
        this.planNo = planNo == null ? null : planNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.tank
     *
     * @return the value of drumtmp.tank
     *
     * @mbggenerated
     */
    public String getTank() {
        return tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.tank
     *
     * @param tank the value for drumtmp.tank
     *
     * @mbggenerated
     */
    public void setTank(String tank) {
        this.tank = tank == null ? null : tank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.time_r
     *
     * @return the value of drumtmp.time_r
     *
     * @mbggenerated
     */
    public String getTimeR() {
        return timeR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.time_r
     *
     * @param timeR the value for drumtmp.time_r
     *
     * @mbggenerated
     */
    public void setTimeR(String timeR) {
        this.timeR = timeR == null ? null : timeR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.date1
     *
     * @return the value of drumtmp.date1
     *
     * @mbggenerated
     */
    public Date getDate1() {
        return date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.date1
     *
     * @param date1 the value for drumtmp.date1
     *
     * @mbggenerated
     */
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.time1
     *
     * @return the value of drumtmp.time1
     *
     * @mbggenerated
     */
    public String getTime1() {
        return time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.time1
     *
     * @param time1 the value for drumtmp.time1
     *
     * @mbggenerated
     */
    public void setTime1(String time1) {
        this.time1 = time1 == null ? null : time1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.weight1
     *
     * @return the value of drumtmp.weight1
     *
     * @mbggenerated
     */
    public Integer getWeight1() {
        return weight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.weight1
     *
     * @param weight1 the value for drumtmp.weight1
     *
     * @mbggenerated
     */
    public void setWeight1(Integer weight1) {
        this.weight1 = weight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.date2
     *
     * @return the value of drumtmp.date2
     *
     * @mbggenerated
     */
    public Date getDate2() {
        return date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.date2
     *
     * @param date2 the value for drumtmp.date2
     *
     * @mbggenerated
     */
    public void setDate2(Date date2) {
        this.date2 = date2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.time2
     *
     * @return the value of drumtmp.time2
     *
     * @mbggenerated
     */
    public String getTime2() {
        return time2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.time2
     *
     * @param time2 the value for drumtmp.time2
     *
     * @mbggenerated
     */
    public void setTime2(String time2) {
        this.time2 = time2 == null ? null : time2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.weight2
     *
     * @return the value of drumtmp.weight2
     *
     * @mbggenerated
     */
    public Integer getWeight2() {
        return weight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.weight2
     *
     * @param weight2 the value for drumtmp.weight2
     *
     * @mbggenerated
     */
    public void setWeight2(Integer weight2) {
        this.weight2 = weight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.vehicle
     *
     * @return the value of drumtmp.vehicle
     *
     * @mbggenerated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.vehicle
     *
     * @param vehicle the value for drumtmp.vehicle
     *
     * @mbggenerated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.vehicle1
     *
     * @return the value of drumtmp.vehicle1
     *
     * @mbggenerated
     */
    public String getVehicle1() {
        return vehicle1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.vehicle1
     *
     * @param vehicle1 the value for drumtmp.vehicle1
     *
     * @mbggenerated
     */
    public void setVehicle1(String vehicle1) {
        this.vehicle1 = vehicle1 == null ? null : vehicle1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.t_customer
     *
     * @return the value of drumtmp.t_customer
     *
     * @mbggenerated
     */
    public String gettCustomer() {
        return tCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.t_customer
     *
     * @param tCustomer the value for drumtmp.t_customer
     *
     * @mbggenerated
     */
    public void settCustomer(String tCustomer) {
        this.tCustomer = tCustomer == null ? null : tCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.c_customer
     *
     * @return the value of drumtmp.c_customer
     *
     * @mbggenerated
     */
    public String getcCustomer() {
        return cCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.c_customer
     *
     * @param cCustomer the value for drumtmp.c_customer
     *
     * @mbggenerated
     */
    public void setcCustomer(String cCustomer) {
        this.cCustomer = cCustomer == null ? null : cCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.s_customer
     *
     * @return the value of drumtmp.s_customer
     *
     * @mbggenerated
     */
    public String getsCustomer() {
        return sCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.s_customer
     *
     * @param sCustomer the value for drumtmp.s_customer
     *
     * @mbggenerated
     */
    public void setsCustomer(String sCustomer) {
        this.sCustomer = sCustomer == null ? null : sCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.billid
     *
     * @return the value of drumtmp.billid
     *
     * @mbggenerated
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.billid
     *
     * @param billid the value for drumtmp.billid
     *
     * @mbggenerated
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.crr_no
     *
     * @return the value of drumtmp.crr_no
     *
     * @mbggenerated
     */
    public String getCrrNo() {
        return crrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.crr_no
     *
     * @param crrNo the value for drumtmp.crr_no
     *
     * @mbggenerated
     */
    public void setCrrNo(String crrNo) {
        this.crrNo = crrNo == null ? null : crrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.do_no
     *
     * @return the value of drumtmp.do_no
     *
     * @mbggenerated
     */
    public String getDoNo() {
        return doNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.do_no
     *
     * @param doNo the value for drumtmp.do_no
     *
     * @mbggenerated
     */
    public void setDoNo(String doNo) {
        this.doNo = doNo == null ? null : doNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.commodity
     *
     * @return the value of drumtmp.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.commodity
     *
     * @param commodity the value for drumtmp.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity == null ? null : commodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.commodity1
     *
     * @return the value of drumtmp.commodity1
     *
     * @mbggenerated
     */
    public String getCommodity1() {
        return commodity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.commodity1
     *
     * @param commodity1 the value for drumtmp.commodity1
     *
     * @mbggenerated
     */
    public void setCommodity1(String commodity1) {
        this.commodity1 = commodity1 == null ? null : commodity1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.drums
     *
     * @return the value of drumtmp.drums
     *
     * @mbggenerated
     */
    public Short getDrums() {
        return drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.drums
     *
     * @param drums the value for drumtmp.drums
     *
     * @mbggenerated
     */
    public void setDrums(Short drums) {
        this.drums = drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.packing
     *
     * @return the value of drumtmp.packing
     *
     * @mbggenerated
     */
    public Integer getPacking() {
        return packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.packing
     *
     * @param packing the value for drumtmp.packing
     *
     * @mbggenerated
     */
    public void setPacking(Integer packing) {
        this.packing = packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.netweight
     *
     * @return the value of drumtmp.netweight
     *
     * @mbggenerated
     */
    public Integer getNetweight() {
        return netweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.netweight
     *
     * @param netweight the value for drumtmp.netweight
     *
     * @mbggenerated
     */
    public void setNetweight(Integer netweight) {
        this.netweight = netweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.new
     *
     * @return the value of drumtmp.new
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.color
     *
     * @return the value of drumtmp.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.color
     *
     * @param color the value for drumtmp.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.tare
     *
     * @return the value of drumtmp.tare
     *
     * @mbggenerated
     */
    public BigDecimal getTare() {
        return tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.tare
     *
     * @param tare the value for drumtmp.tare
     *
     * @mbggenerated
     */
    public void setTare(BigDecimal tare) {
        this.tare = tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.cover
     *
     * @return the value of drumtmp.cover
     *
     * @mbggenerated
     */
    public Boolean getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.cover
     *
     * @param cover the value for drumtmp.cover
     *
     * @mbggenerated
     */
    public void setCover(Boolean cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.batch
     *
     * @return the value of drumtmp.batch
     *
     * @mbggenerated
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.batch
     *
     * @param batch the value for drumtmp.batch
     *
     * @mbggenerated
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.slop
     *
     * @return the value of drumtmp.slop
     *
     * @mbggenerated
     */
    public Boolean getSlop() {
        return slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.slop
     *
     * @param slop the value for drumtmp.slop
     *
     * @mbggenerated
     */
    public void setSlop(Boolean slop) {
        this.slop = slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.type
     *
     * @return the value of drumtmp.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.type
     *
     * @param type the value for drumtmp.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.delivered
     *
     * @return the value of drumtmp.delivered
     *
     * @mbggenerated
     */
    public String getDelivered() {
        return delivered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.delivered
     *
     * @param delivered the value for drumtmp.delivered
     *
     * @mbggenerated
     */
    public void setDelivered(String delivered) {
        this.delivered = delivered == null ? null : delivered.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.serial
     *
     * @return the value of drumtmp.serial
     *
     * @mbggenerated
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.serial
     *
     * @param serial the value for drumtmp.serial
     *
     * @mbggenerated
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.status
     *
     * @return the value of drumtmp.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.status
     *
     * @param status the value for drumtmp.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.station
     *
     * @return the value of drumtmp.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.station
     *
     * @param station the value for drumtmp.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.remarks
     *
     * @return the value of drumtmp.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.remarks
     *
     * @param remarks the value for drumtmp.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.isin
     *
     * @return the value of drumtmp.isin
     *
     * @mbggenerated
     */
    public Boolean getIsin() {
        return isin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.isin
     *
     * @param isin the value for drumtmp.isin
     *
     * @mbggenerated
     */
    public void setIsin(Boolean isin) {
        this.isin = isin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.sendno
     *
     * @return the value of drumtmp.sendno
     *
     * @mbggenerated
     */
    public String getSendno() {
        return sendno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.sendno
     *
     * @param sendno the value for drumtmp.sendno
     *
     * @mbggenerated
     */
    public void setSendno(String sendno) {
        this.sendno = sendno == null ? null : sendno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.idno
     *
     * @return the value of drumtmp.idno
     *
     * @mbggenerated
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.idno
     *
     * @param idno the value for drumtmp.idno
     *
     * @mbggenerated
     */
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.ori_do
     *
     * @return the value of drumtmp.ori_do
     *
     * @mbggenerated
     */
    public Boolean getOriDo() {
        return oriDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.ori_do
     *
     * @param oriDo the value for drumtmp.ori_do
     *
     * @mbggenerated
     */
    public void setOriDo(Boolean oriDo) {
        this.oriDo = oriDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.faxno
     *
     * @return the value of drumtmp.faxno
     *
     * @mbggenerated
     */
    public String getFaxno() {
        return faxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.faxno
     *
     * @param faxno the value for drumtmp.faxno
     *
     * @mbggenerated
     */
    public void setFaxno(String faxno) {
        this.faxno = faxno == null ? null : faxno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.charge
     *
     * @return the value of drumtmp.charge
     *
     * @mbggenerated
     */
    public Boolean getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.charge
     *
     * @param charge the value for drumtmp.charge
     *
     * @mbggenerated
     */
    public void setCharge(Boolean charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.fee_no
     *
     * @return the value of drumtmp.fee_no
     *
     * @mbggenerated
     */
    public String getFeeNo() {
        return feeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.fee_no
     *
     * @param feeNo the value for drumtmp.fee_no
     *
     * @mbggenerated
     */
    public void setFeeNo(String feeNo) {
        this.feeNo = feeNo == null ? null : feeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.fee
     *
     * @return the value of drumtmp.fee
     *
     * @mbggenerated
     */
    public Short getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.fee
     *
     * @param fee the value for drumtmp.fee
     *
     * @mbggenerated
     */
    public void setFee(Short fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.jobno
     *
     * @return the value of drumtmp.jobno
     *
     * @mbggenerated
     */
    public String getJobno() {
        return jobno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.jobno
     *
     * @param jobno the value for drumtmp.jobno
     *
     * @mbggenerated
     */
    public void setJobno(String jobno) {
        this.jobno = jobno == null ? null : jobno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.code
     *
     * @return the value of drumtmp.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.code
     *
     * @param code the value for drumtmp.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drumtmp.p_bar
     *
     * @return the value of drumtmp.p_bar
     *
     * @mbggenerated
     */
    public Boolean getpBar() {
        return pBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drumtmp.p_bar
     *
     * @param pBar the value for drumtmp.p_bar
     *
     * @mbggenerated
     */
    public void setpBar(Boolean pBar) {
        this.pBar = pBar;
    }
}