package com.yshyerp.vehicle.entity;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
@Data
public class EDrumtmp implements Serializable {

    private String d;


    private String idno;


    private String jobno;


    private String draNo;


    private String planNo;

    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.s_customer
     *
     * @mbggenerated
     */
    private String sCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.billid
     *
     * @mbggenerated
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.vehicle
     *
     * @mbggenerated
     */
    private String vehicle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.vehicle1
     *
     * @mbggenerated
     */
    private String vehicle1;


    private Date date;


    private String n;


    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.tare
     *
     * @mbggenerated
     */
    private BigDecimal tare;


    private Boolean cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.drums
     *
     * @mbggenerated
     */
    private Short drums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.come
     *
     * @mbggenerated
     */
    private String come;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.time1
     *
     * @mbggenerated
     */
    private String time1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.time2
     *
     * @mbggenerated
     */
    private String time2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.weight1
     *
     * @mbggenerated
     */
    private Integer weight1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.weight2
     *
     * @mbggenerated
     */
    private Integer weight2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.charge
     *
     * @mbggenerated
     */
    private Boolean charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.original
     *
     * @mbggenerated
     */
    private Boolean original;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.faxno
     *
     * @mbggenerated
     */
    private String faxno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_drumtmp.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table e_drumtmp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.d
     *
     * @return the value of e_drumtmp.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.d
     *
     * @param d the value for e_drumtmp.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.idno
     *
     * @return the value of e_drumtmp.idno
     *
     * @mbggenerated
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.idno
     *
     * @param idno the value for e_drumtmp.idno
     *
     * @mbggenerated
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.jobno
     *
     * @return the value of e_drumtmp.jobno
     *
     * @mbggenerated
     */
    public String getJobno() {
        return jobno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.jobno
     *
     * @param jobno the value for e_drumtmp.jobno
     *
     * @mbggenerated
     */
    public void setJobno(String jobno) {
        this.jobno = jobno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.dra_no
     *
     * @return the value of e_drumtmp.dra_no
     *
     * @mbggenerated
     */
    public String getDraNo() {
        return draNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.dra_no
     *
     * @param draNo the value for e_drumtmp.dra_no
     *
     * @mbggenerated
     */
    public void setDraNo(String draNo) {
        this.draNo = draNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.plan_no
     *
     * @return the value of e_drumtmp.plan_no
     *
     * @mbggenerated
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.plan_no
     *
     * @param planNo the value for e_drumtmp.plan_no
     *
     * @mbggenerated
     */
    public void setPlanNo(String planNo) {
        this.planNo = planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.customer
     *
     * @return the value of e_drumtmp.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.customer
     *
     * @param customer the value for e_drumtmp.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.s_customer
     *
     * @return the value of e_drumtmp.s_customer
     *
     * @mbggenerated
     */
    public String getsCustomer() {
        return sCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.s_customer
     *
     * @param sCustomer the value for e_drumtmp.s_customer
     *
     * @mbggenerated
     */
    public void setsCustomer(String sCustomer) {
        this.sCustomer = sCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.billid
     *
     * @return the value of e_drumtmp.billid
     *
     * @mbggenerated
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.billid
     *
     * @param billid the value for e_drumtmp.billid
     *
     * @mbggenerated
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.vehicle
     *
     * @return the value of e_drumtmp.vehicle
     *
     * @mbggenerated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.vehicle
     *
     * @param vehicle the value for e_drumtmp.vehicle
     *
     * @mbggenerated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.vehicle1
     *
     * @return the value of e_drumtmp.vehicle1
     *
     * @mbggenerated
     */
    public String getVehicle1() {
        return vehicle1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.vehicle1
     *
     * @param vehicle1 the value for e_drumtmp.vehicle1
     *
     * @mbggenerated
     */
    public void setVehicle1(String vehicle1) {
        this.vehicle1 = vehicle1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.date
     *
     * @return the value of e_drumtmp.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.date
     *
     * @param date the value for e_drumtmp.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    public String getN() {
        return n;
    }

    public void setN(String n) {
        this.n = n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.color
     *
     * @return the value of e_drumtmp.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.color
     *
     * @param color the value for e_drumtmp.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.tare
     *
     * @return the value of e_drumtmp.tare
     *
     * @mbggenerated
     */
    public BigDecimal getTare() {
        return tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.tare
     *
     * @param tare the value for e_drumtmp.tare
     *
     * @mbggenerated
     */
    public void setTare(BigDecimal tare) {
        this.tare = tare;
    }


    public Short getDrums() {
        return drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.drums
     *
     * @param drums the value for e_drumtmp.drums
     *
     * @mbggenerated
     */
    public void setDrums(Short drums) {
        this.drums = drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.come
     *
     * @return the value of e_drumtmp.come
     *
     * @mbggenerated
     */
    public String getCome() {
        return come;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.come
     *
     * @param come the value for e_drumtmp.come
     *
     * @mbggenerated
     */
    public void setCome(String come) {
        this.come = come;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.time1
     *
     * @return the value of e_drumtmp.time1
     *
     * @mbggenerated
     */
    public String getTime1() {
        return time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.time1
     *
     * @param time1 the value for e_drumtmp.time1
     *
     * @mbggenerated
     */
    public void setTime1(String time1) {
        this.time1 = time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.time2
     *
     * @return the value of e_drumtmp.time2
     *
     * @mbggenerated
     */
    public String getTime2() {
        return time2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.time2
     *
     * @param time2 the value for e_drumtmp.time2
     *
     * @mbggenerated
     */
    public void setTime2(String time2) {
        this.time2 = time2;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.charge
     *
     * @return the value of e_drumtmp.charge
     *
     * @mbggenerated
     */
    public Boolean getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.charge
     *
     * @param charge the value for e_drumtmp.charge
     *
     * @mbggenerated
     */
    public void setCharge(Boolean charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.original
     *
     * @return the value of e_drumtmp.original
     *
     * @mbggenerated
     */
    public Boolean getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.original
     *
     * @param original the value for e_drumtmp.original
     *
     * @mbggenerated
     */
    public void setOriginal(Boolean original) {
        this.original = original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.faxno
     *
     * @return the value of e_drumtmp.faxno
     *
     * @mbggenerated
     */
    public String getFaxno() {
        return faxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.faxno
     *
     * @param faxno the value for e_drumtmp.faxno
     *
     * @mbggenerated
     */
    public void setFaxno(String faxno) {
        this.faxno = faxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_drumtmp.remarks
     *
     * @return the value of e_drumtmp.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_drumtmp.remarks
     *
     * @param remarks the value for e_drumtmp.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}