package com.yshyerp.vehicle.entity;

import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 储罐
 */
@Data
public class Tank implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.code1
     *
     * @mbggenerated
     */
    private String code1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tank
     *
     * @mbggenerated
     */
    private String tank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tax
     *
     * @mbggenerated
     */
    private Boolean tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.batch_no
     *
     * @mbggenerated
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.t_customer
     *
     * @mbggenerated
     */
    private String tCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.c_customer
     *
     * @mbggenerated
     */
    private String cCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.oil
     *
     * @mbggenerated
     */
    private Boolean oil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.oil_o
     *
     * @mbggenerated
     */
    private Boolean oilO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tank_h
     *
     * @mbggenerated
     */
    private String tankH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.max_h
     *
     * @mbggenerated
     */
    private String maxH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.max_v
     *
     * @mbggenerated
     */
    private String maxV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.safety_h
     *
     * @mbggenerated
     */
    private String safetyH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.safety_v
     *
     * @mbggenerated
     */
    private String safetyV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.klitre_cm
     *
     * @mbggenerated
     */
    private String klitreCm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.pipe_line
     *
     * @mbggenerated
     */
    private String pipeLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.gauge_m
     *
     * @mbggenerated
     */
    private BigDecimal gaugeM;

    //密度
    private BigDecimal density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.m_balance
     *
     * @mbggenerated
     */
    private Integer mBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.h_quan
     *
     * @mbggenerated
     */
    private Integer hQuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.lowest_vol
     *
     * @mbggenerated
     */
    private BigDecimal lowestVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.limit_vol
     *
     * @mbggenerated
     */
    private BigDecimal limitVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crr_vol
     *
     * @mbggenerated
     */
    private BigDecimal crrVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crr_vol_use
     *
     * @mbggenerated
     */
    private Boolean crrVolUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.lock_tank
     *
     * @mbggenerated
     */
    private Boolean lockTank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.phase
     *
     * @mbggenerated
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.commence
     *
     * @mbggenerated
     */
    private Date commence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.thruput_mi
     *
     * @mbggenerated
     */
    private Integer thruputMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.station1
     *
     * @mbggenerated
     */
    private String station1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.station2
     *
     * @mbggenerated
     */
    private String station2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.station3
     *
     * @mbggenerated
     */
    private String station3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.c_status
     *
     * @mbggenerated
     */
    private Boolean cStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.t_use
     *
     * @mbggenerated
     */
    private String tUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.last_comm
     *
     * @mbggenerated
     */
    private String lastComm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tenant
     *
     * @mbggenerated
     */
    private String tenant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.update_d
     *
     * @mbggenerated
     */
    private Date updateD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crc
     *
     * @mbggenerated
     */
    private Boolean crc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crc_1
     *
     * @mbggenerated
     */
    private Boolean crc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.coa
     *
     * @mbggenerated
     */
    private Boolean coa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.coa1
     *
     * @mbggenerated
     */
    private String coa1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.coa_p
     *
     * @mbggenerated
     */
    private Short coaP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crr_use
     *
     * @mbggenerated
     */
    private Boolean crrUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.fd
     *
     * @mbggenerated
     */
    private Boolean fd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.fd_weight
     *
     * @mbggenerated
     */
    private BigDecimal fdWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.q1
     *
     * @mbggenerated
     */
    private Integer q1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.q2
     *
     * @mbggenerated
     */
    private Integer q2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.bs
     *
     * @mbggenerated
     */
    private Boolean bs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.g_type
     *
     * @mbggenerated
     */
    private String gType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.r
     *
     * @mbggenerated
     */
    private BigDecimal r;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.t
     *
     * @mbggenerated
     */
    private Short t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.m
     *
     * @mbggenerated
     */
    private BigDecimal m;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.xfz
     *
     * @mbggenerated
     */
    private Boolean xfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.temp1
     *
     * @mbggenerated
     */
    private BigDecimal temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.temp2
     *
     * @mbggenerated
     */
    private BigDecimal temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.n2
     *
     * @mbggenerated
     */
    private String n2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.hot
     *
     * @mbggenerated
     */
    private Boolean hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.cool
     *
     * @mbggenerated
     */
    private Boolean cool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tg
     *
     * @mbggenerated
     */
    private Boolean tg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.bw
     *
     * @mbggenerated
     */
    private Boolean bw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.jr
     *
     * @mbggenerated
     */
    private String jr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.hx
     *
     * @mbggenerated
     */
    private Boolean hx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.zh
     *
     * @mbggenerated
     */
    private Boolean zh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.u_date
     *
     * @mbggenerated
     */
    private Date uDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.allow_comm
     *
     * @mbggenerated
     */
    private String allowComm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tank
     *
     * @mbggenerated
     */

    private BigDecimal qDifference;

    private static final long serialVersionUID = 1L;

}