package com.yshyerp.vehicle.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class TranE implements Serializable {

    private Double tele;


    private String licence;


    private String name;


    private String address;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tran_e.tele
     *
     * @return the value of tran_e.tele
     *
     * @mbggenerated
     */
    public Double getTele() {
        return tele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tran_e.tele
     *
     * @param tele the value for tran_e.tele
     *
     * @mbggenerated
     */
    public void setTele(Double tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tran_e.licence
     *
     * @return the value of tran_e.licence
     *
     * @mbggenerated
     */
    public String getLicence() {
        return licence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tran_e.licence
     *
     * @param licence the value for tran_e.licence
     *
     * @mbggenerated
     */
    public void setLicence(String licence) {
        this.licence = licence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tran_e.name
     *
     * @return the value of tran_e.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tran_e.name
     *
     * @param name the value for tran_e.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tran_e.address
     *
     * @return the value of tran_e.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tran_e.address
     *
     * @param address the value for tran_e.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }
}