package com.yshyerp.vehicle.entity;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

@Data
public class VehiPlan1 implements Serializable {

    private Integer id;

    private String typea;
    private String d;


    private String planType;


    private String planNo;


    private Integer billid;

    private String contractI;


    private String vehicle;

    private String vehicle1;


    private BigDecimal vehiV;


    private BigDecimal vehiW;


    private BigDecimal vehiW1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.vehi_w2
     *
     * @mbggenerated
     */
    private BigDecimal vehiW2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.vehi_w3
     *
     * @mbggenerated
     */
    private BigDecimal vehiW3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.c_no
     *
     * @mbggenerated
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.idno
     *
     * @mbggenerated
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.r_date
     *
     * @mbggenerated
     */
    private Date rDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.d_date
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",  timezone="GMT+8")
    private Timestamp dDate;

    public Timestamp getdDate() {
        return dDate;
    }

    public void setdDate(Timestamp dDate) {
        this.dDate = dDate;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.v_date
     *
     * @mbggenerated
     */
    private Integer vDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.original
     *
     * @mbggenerated
     */
    private Boolean original;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.bdo
     *
     * @mbggenerated
     */
    private Boolean bdo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.faxno
     *
     * @mbggenerated
     */
    private String faxno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.t_customer
     *
     * @mbggenerated
     */
    private String tCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.c_customer
     *
     * @mbggenerated
     */
    private String cCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.s_customer
     *
     * @mbggenerated
     */
    private String sCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.commodity1
     *
     * @mbggenerated
     */
    private String commodity1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.tank
     *
     * @mbggenerated
     */
    private String tank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.crr_no
     *
     * @mbggenerated
     */
    private String crrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.do_no
     *
     * @mbggenerated
     */
    private String doNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.quantity
     *
     * @mbggenerated
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.delivered
     *
     * @mbggenerated
     */
    private String delivered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.tno1
     *
     * @mbggenerated
     */
    private String tno1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.no1
     *
     * @mbggenerated
     */
    private String no1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.drums
     *
     * @mbggenerated
     */
    private Short drums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.packing
     *
     * @mbggenerated
     */
    private Integer packing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.netweight
     *
     * @mbggenerated
     */
    private Integer netweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.new
     *
     * @mbggenerated
     */
   private String cnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.tare
     *
     * @mbggenerated
     */
    private BigDecimal tare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.cover
     *
     * @mbggenerated
     */
    private Boolean cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.batch
     *
     * @mbggenerated
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.come
     *
     * @mbggenerated
     */
    private String come;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.slop
     *
     * @mbggenerated
     */
    private Boolean slop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.p_bar
     *
     * @mbggenerated
     */
    private Boolean pBar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehi_plan.jobno
     *
     * @mbggenerated
     */
    private String jobno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vehi_plan
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.id
     *
     * @return the value of vehi_plan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.id
     *
     * @param id the value for vehi_plan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.d
     *
     * @return the value of vehi_plan.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.d
     *
     * @param d the value for vehi_plan.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.plan_type
     *
     * @return the value of vehi_plan.plan_type
     *
     * @mbggenerated
     */
    public String getPlanType() {
        return planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.plan_type
     *
     * @param planType the value for vehi_plan.plan_type
     *
     * @mbggenerated
     */
    public void setPlanType(String planType) {
        this.planType = planType == null ? null : planType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.plan_no
     *
     * @return the value of vehi_plan.plan_no
     *
     * @mbggenerated
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.plan_no
     *
     * @param planNo the value for vehi_plan.plan_no
     *
     * @mbggenerated
     */
    public void setPlanNo(String planNo) {
        this.planNo = planNo == null ? null : planNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.billid
     *
     * @return the value of vehi_plan.billid
     *
     * @mbggenerated
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.billid
     *
     * @param billid the value for vehi_plan.billid
     *
     * @mbggenerated
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.contract_i
     *
     * @return the value of vehi_plan.contract_i
     *
     * @mbggenerated
     */
    public String getContractI() {
        return contractI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.contract_i
     *
     * @param contractI the value for vehi_plan.contract_i
     *
     * @mbggenerated
     */
    public void setContractI(String contractI) {
        this.contractI = contractI == null ? null : contractI.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehicle
     *
     * @return the value of vehi_plan.vehicle
     *
     * @mbggenerated
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehicle
     *
     * @param vehicle the value for vehi_plan.vehicle
     *
     * @mbggenerated
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle == null ? null : vehicle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehicle1
     *
     * @return the value of vehi_plan.vehicle1
     *
     * @mbggenerated
     */
    public String getVehicle1() {
        return vehicle1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehicle1
     *
     * @param vehicle1 the value for vehi_plan.vehicle1
     *
     * @mbggenerated
     */
    public void setVehicle1(String vehicle1) {
        this.vehicle1 = vehicle1 == null ? null : vehicle1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehi_v
     *
     * @return the value of vehi_plan.vehi_v
     *
     * @mbggenerated
     */
    public BigDecimal getVehiV() {
        return vehiV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehi_v
     *
     * @param vehiV the value for vehi_plan.vehi_v
     *
     * @mbggenerated
     */
    public void setVehiV(BigDecimal vehiV) {
        this.vehiV = vehiV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehi_w
     *
     * @return the value of vehi_plan.vehi_w
     *
     * @mbggenerated
     */
    public BigDecimal getVehiW() {
        return vehiW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehi_w
     *
     * @param vehiW the value for vehi_plan.vehi_w
     *
     * @mbggenerated
     */
    public void setVehiW(BigDecimal vehiW) {
        this.vehiW = vehiW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehi_w1
     *
     * @return the value of vehi_plan.vehi_w1
     *
     * @mbggenerated
     */
    public BigDecimal getVehiW1() {
        return vehiW1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehi_w1
     *
     * @param vehiW1 the value for vehi_plan.vehi_w1
     *
     * @mbggenerated
     */
    public void setVehiW1(BigDecimal vehiW1) {
        this.vehiW1 = vehiW1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehi_w2
     *
     * @return the value of vehi_plan.vehi_w2
     *
     * @mbggenerated
     */
    public BigDecimal getVehiW2() {
        return vehiW2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehi_w2
     *
     * @param vehiW2 the value for vehi_plan.vehi_w2
     *
     * @mbggenerated
     */
    public void setVehiW2(BigDecimal vehiW2) {
        this.vehiW2 = vehiW2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.vehi_w3
     *
     * @return the value of vehi_plan.vehi_w3
     *
     * @mbggenerated
     */
    public BigDecimal getVehiW3() {
        return vehiW3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.vehi_w3
     *
     * @param vehiW3 the value for vehi_plan.vehi_w3
     *
     * @mbggenerated
     */
    public void setVehiW3(BigDecimal vehiW3) {
        this.vehiW3 = vehiW3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.c_no
     *
     * @return the value of vehi_plan.c_no
     *
     * @mbggenerated
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.c_no
     *
     * @param cNo the value for vehi_plan.c_no
     *
     * @mbggenerated
     */
    public void setcNo(String cNo) {
        this.cNo = cNo == null ? null : cNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.idno
     *
     * @return the value of vehi_plan.idno
     *
     * @mbggenerated
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.idno
     *
     * @param idno the value for vehi_plan.idno
     *
     * @mbggenerated
     */
    public void setIdno(String idno) {
        this.idno = idno == null ? null : idno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.r_date
     *
     * @return the value of vehi_plan.r_date
     *
     * @mbggenerated
     */
    public Date getrDate() {
        return rDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.r_date
     *
     * @param rDate the value for vehi_plan.r_date
     *
     * @mbggenerated
     */
    public void setrDate(Date rDate) {
        this.rDate = rDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.d_date
     *
     * @return the value of vehi_plan.d_date
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.v_date
     *
     * @return the value of vehi_plan.v_date
     *
     * @mbggenerated
     */
    public Integer getvDate() {
        return vDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.v_date
     *
     * @param vDate the value for vehi_plan.v_date
     *
     * @mbggenerated
     */
    public void setvDate(Integer vDate) {
        this.vDate = vDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.original
     *
     * @return the value of vehi_plan.original
     *
     * @mbggenerated
     */
    public Boolean getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.original
     *
     * @param original the value for vehi_plan.original
     *
     * @mbggenerated
     */
    public void setOriginal(Boolean original) {
        this.original = original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.bdo
     *
     * @return the value of vehi_plan.bdo
     *
     * @mbggenerated
     */
    public Boolean getBdo() {
        return bdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.bdo
     *
     * @param bdo the value for vehi_plan.bdo
     *
     * @mbggenerated
     */
    public void setBdo(Boolean bdo) {
        this.bdo = bdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.faxno
     *
     * @return the value of vehi_plan.faxno
     *
     * @mbggenerated
     */
    public String getFaxno() {
        return faxno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.faxno
     *
     * @param faxno the value for vehi_plan.faxno
     *
     * @mbggenerated
     */
    public void setFaxno(String faxno) {
        this.faxno = faxno == null ? null : faxno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.t_customer
     *
     * @return the value of vehi_plan.t_customer
     *
     * @mbggenerated
     */
    public String gettCustomer() {
        return tCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.t_customer
     *
     * @param tCustomer the value for vehi_plan.t_customer
     *
     * @mbggenerated
     */
    public void settCustomer(String tCustomer) {
        this.tCustomer = tCustomer == null ? null : tCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.c_customer
     *
     * @return the value of vehi_plan.c_customer
     *
     * @mbggenerated
     */
    public String getcCustomer() {
        return cCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.c_customer
     *
     * @param cCustomer the value for vehi_plan.c_customer
     *
     * @mbggenerated
     */
    public void setcCustomer(String cCustomer) {
        this.cCustomer = cCustomer == null ? null : cCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.s_customer
     *
     * @return the value of vehi_plan.s_customer
     *
     * @mbggenerated
     */
    public String getsCustomer() {
        return sCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.s_customer
     *
     * @param sCustomer the value for vehi_plan.s_customer
     *
     * @mbggenerated
     */
    public void setsCustomer(String sCustomer) {
        this.sCustomer = sCustomer == null ? null : sCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.commodity
     *
     * @return the value of vehi_plan.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.commodity
     *
     * @param commodity the value for vehi_plan.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity == null ? null : commodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.commodity1
     *
     * @return the value of vehi_plan.commodity1
     *
     * @mbggenerated
     */
    public String getCommodity1() {
        return commodity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.commodity1
     *
     * @param commodity1 the value for vehi_plan.commodity1
     *
     * @mbggenerated
     */
    public void setCommodity1(String commodity1) {
        this.commodity1 = commodity1 == null ? null : commodity1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.tank
     *
     * @return the value of vehi_plan.tank
     *
     * @mbggenerated
     */
    public String getTank() {
        return tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.tank
     *
     * @param tank the value for vehi_plan.tank
     *
     * @mbggenerated
     */
    public void setTank(String tank) {
        this.tank = tank == null ? null : tank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.crr_no
     *
     * @return the value of vehi_plan.crr_no
     *
     * @mbggenerated
     */
    public String getCrrNo() {
        return crrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.crr_no
     *
     * @param crrNo the value for vehi_plan.crr_no
     *
     * @mbggenerated
     */
    public void setCrrNo(String crrNo) {
        this.crrNo = crrNo == null ? null : crrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.do_no
     *
     * @return the value of vehi_plan.do_no
     *
     * @mbggenerated
     */
    public String getDoNo() {
        return doNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.do_no
     *
     * @param doNo the value for vehi_plan.do_no
     *
     * @mbggenerated
     */
    public void setDoNo(String doNo) {
        this.doNo = doNo == null ? null : doNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.quantity
     *
     * @return the value of vehi_plan.quantity
     *
     * @mbggenerated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.quantity
     *
     * @param quantity the value for vehi_plan.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.remarks
     *
     * @return the value of vehi_plan.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.remarks
     *
     * @param remarks the value for vehi_plan.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.delivered
     *
     * @return the value of vehi_plan.delivered
     *
     * @mbggenerated
     */
    public String getDelivered() {
        return delivered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.delivered
     *
     * @param delivered the value for vehi_plan.delivered
     *
     * @mbggenerated
     */
    public void setDelivered(String delivered) {
        this.delivered = delivered == null ? null : delivered.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.tno1
     *
     * @return the value of vehi_plan.tno1
     *
     * @mbggenerated
     */
    public String getTno1() {
        return tno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.tno1
     *
     * @param tno1 the value for vehi_plan.tno1
     *
     * @mbggenerated
     */
    public void setTno1(String tno1) {
        this.tno1 = tno1 == null ? null : tno1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.no1
     *
     * @return the value of vehi_plan.no1
     *
     * @mbggenerated
     */
    public String getNo1() {
        return no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.no1
     *
     * @param no1 the value for vehi_plan.no1
     *
     * @mbggenerated
     */
    public void setNo1(String no1) {
        this.no1 = no1 == null ? null : no1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.drums
     *
     * @return the value of vehi_plan.drums
     *
     * @mbggenerated
     */
    public Short getDrums() {
        return drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.drums
     *
     * @param drums the value for vehi_plan.drums
     *
     * @mbggenerated
     */
    public void setDrums(Short drums) {
        this.drums = drums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.packing
     *
     * @return the value of vehi_plan.packing
     *
     * @mbggenerated
     */
    public Integer getPacking() {
        return packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.packing
     *
     * @param packing the value for vehi_plan.packing
     *
     * @mbggenerated
     */
    public void setPacking(Integer packing) {
        this.packing = packing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.netweight
     *
     * @return the value of vehi_plan.netweight
     *
     * @mbggenerated
     */
    public Integer getNetweight() {
        return netweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.netweight
     *
     * @param netweight the value for vehi_plan.netweight
     *
     * @mbggenerated
     */
    public void setNetweight(Integer netweight) {
        this.netweight = netweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.new
     *
     * @return the value of vehi_plan.new
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.color
     *
     * @return the value of vehi_plan.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.color
     *
     * @param color the value for vehi_plan.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.tare
     *
     * @return the value of vehi_plan.tare
     *
     * @mbggenerated
     */
    public BigDecimal getTare() {
        return tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.tare
     *
     * @param tare the value for vehi_plan.tare
     *
     * @mbggenerated
     */
    public void setTare(BigDecimal tare) {
        this.tare = tare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.cover
     *
     * @return the value of vehi_plan.cover
     *
     * @mbggenerated
     */
    public Boolean getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.cover
     *
     * @param cover the value for vehi_plan.cover
     *
     * @mbggenerated
     */
    public void setCover(Boolean cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.batch
     *
     * @return the value of vehi_plan.batch
     *
     * @mbggenerated
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.batch
     *
     * @param batch the value for vehi_plan.batch
     *
     * @mbggenerated
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.come
     *
     * @return the value of vehi_plan.come
     *
     * @mbggenerated
     */
    public String getCome() {
        return come;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.come
     *
     * @param come the value for vehi_plan.come
     *
     * @mbggenerated
     */
    public void setCome(String come) {
        this.come = come == null ? null : come.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.slop
     *
     * @return the value of vehi_plan.slop
     *
     * @mbggenerated
     */
    public Boolean getSlop() {
        return slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.slop
     *
     * @param slop the value for vehi_plan.slop
     *
     * @mbggenerated
     */
    public void setSlop(Boolean slop) {
        this.slop = slop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.type
     *
     * @return the value of vehi_plan.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.type
     *
     * @param type the value for vehi_plan.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.status
     *
     * @return the value of vehi_plan.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.status
     *
     * @param status the value for vehi_plan.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.code
     *
     * @return the value of vehi_plan.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.code
     *
     * @param code the value for vehi_plan.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.p_bar
     *
     * @return the value of vehi_plan.p_bar
     *
     * @mbggenerated
     */
    public Boolean getpBar() {
        return pBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.p_bar
     *
     * @param pBar the value for vehi_plan.p_bar
     *
     * @mbggenerated
     */
    public void setpBar(Boolean pBar) {
        this.pBar = pBar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.state
     *
     * @return the value of vehi_plan.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.state
     *
     * @param state the value for vehi_plan.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehi_plan.jobno
     *
     * @return the value of vehi_plan.jobno
     *
     * @mbggenerated
     */
    public String getJobno() {
        return jobno;
    }

    public String getCnew() {
        return cnew;
    }

    public void setCnew(String cnew) {
        this.cnew = cnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehi_plan.jobno
     *
     * @param jobno the value for vehi_plan.jobno
     *
     * @mbggenerated
     */
    public void setJobno(String jobno) {
        this.jobno = jobno == null ? null : jobno.trim();
    }
}